class Addabsen < ActiveRecord::Migration[5.0]
  def change
    add_column(:mahasiswa_kelas, :abs1, :integer)
    add_column(:mahasiswa_kelas, :abs2, :integer)
    add_column(:mahasiswa_kelas, :abs3, :integer)
    add_column(:mahasiswa_kelas, :abs4, :integer)
    add_column(:mahasiswa_kelas, :abs5, :integer)
    add_column(:mahasiswa_kelas, :abs6, :integer)
    add_column(:mahasiswa_kelas, :abs7, :integer)
    add_column(:mahasiswa_kelas, :abs8, :integer)
    add_column(:mahasiswa_kelas, :abs9, :integer)
    add_column(:mahasiswa_kelas, :abs10, :integer)
    add_column(:mahasiswa_kelas, :abs11, :integer)
    add_column(:mahasiswa_kelas, :abs12, :integer)
    add_column(:mahasiswa_kelas, :abs13, :integer)
    add_column(:mahasiswa_kelas, :abs14, :integer)
    add_column(:mahasiswa_kelas, :abs15, :integer)
    add_column(:mahasiswa_kelas, :abs16, :integer)
    add_column(:mahasiswa_kelas, :abs17, :integer)
    add_column(:mahasiswa_kelas, :abs18, :integer)
    add_column(:mahasiswa_kelas, :abs19, :integer)
    add_column(:mahasiswa_kelas, :abs20, :integer)
    add_column(:mahasiswa_kelas, :abs21, :integer)
    add_column(:mahasiswa_kelas, :abs22, :integer)
    add_column(:mahasiswa_kelas, :abs23, :integer)
    add_column(:mahasiswa_kelas, :abs24, :integer)
    add_column(:mahasiswa_kelas, :abs25, :integer)
    add_column(:mahasiswa_kelas, :abs26, :integer)
    add_column(:mahasiswa_kelas, :abs27, :integer)
    add_column(:mahasiswa_kelas, :abs28, :integer)
    add_column(:mahasiswa_kelas, :quiz, :decimal, :precision => 64, :scale => 12)
    add_column(:mahasiswa_kelas, :uts, :decimal, :precision => 64, :scale => 12)
    add_column(:mahasiswa_kelas, :uas, :decimal, :precision => 64, :scale => 12)
    add_column(:mahasiswa_kelas, :tugas, :decimal, :precision => 64, :scale => 12)
  end
end
